name: Precure News Bot

on:
  workflow_dispatch:
  repository_dispatch:
    types: [cron]
permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリ取得
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Pythonセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: ライブラリインストール
        run: pip install -r requirements.txt

      - name: Bot起動
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python main.py

      - name: 保存
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update last posts $(date '+%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
