name: Precure News Bot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリ取得
        uses: actions/checkout@v4

      - name: Pythonセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: ライブラリインストール
        run: pip install -r requirements.txt

      - name: Bot起動
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python main.py

      - name: 確認
        run: |
          ls
          git status

      - name: 保存
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add last_posts.json
          git commit -m "Update last posts" || exit 0
          git push
